import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://talesofdeutsch.vercel.app"),
  title: "About | Tales of Deutsch",
  description: "Learn about Tales of Deutsch, a platform designed to help you learn German through immersive storytelling.",
  openGraph: {
    title: "About | Tales of Deutsch",
    description: "Learn about Tales of Deutsch, a platform designed to help you learn German through immersive storytelling.",
    type: "website",
    images: [
      {
        url: "/images/tales-of-deutsch.png",
        width: 1200,
        height: 630,
        alt: "Tales of Deutsch",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "About | Tales of Deutsch",
    description: "Learn about Tales of Deutsch, a platform designed to help you learn German through immersive storytelling.",
    images: ["/images/tales-of-deutsch.png"],
  },
};

export default function About() {
  return (
    <main className="min-h-screen p-8 pb-16">
      <Link 
        href="/" 
        className="inline-block mb-8 text-accent hover:underline"
      >
        ← Back to Home
      </Link>
      
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-semibold mb-8">About Tales of Deutsch</h1>
        
        <div className="prose prose-lg dark:prose-invert">
          <p>
            Tales of Deutsch is a platform designed to help you learn German through immersive storytelling.
          </p>
          <p>
            Our interactive stories allow you to read German text with on-demand translations and word definitions,
            making the learning process more engaging and effective.
          </p>
          <h2>Features</h2>
          <ul>
            <li>Interactive German stories with paragraph-by-paragraph translations</li>
            <li>Click on any word to see its definition and pronunciation</li>
            <li>Progressive learning with stories of varying difficulty levels</li>
          </ul>
        </div>
        
        {/* Subtle AI-generated content notification */}
        <div className="mt-16 pt-4 border-t border-gray-200 dark:border-gray-700 text-center opacity-75">
          <p className="text-xs text-text-secondary">
            Stories and translations are generated by LLMs.
          </p>
        </div>
      </div>
    </main>
  );
}