"use client";

import { useQuery } from "@tanstack/react-query";
import StoryCard from "@/components/StoryCard";
import Link from "next/link";
import { Story } from "@/types/story";

// Function to fetch stories
const fetchStories = async (): Promise<Story[]> => {
  const response = await fetch('/api/stories');
  if (!response.ok) {
    throw new Error('Failed to fetch stories');
  }
  return response.json();
};

export default function StoriesPage() {
  // Using React Query to fetch stories
  const { data: stories, isLoading, error } = useQuery({
    queryKey: ['stories'],
    queryFn: fetchStories,
  });

  return (
    <main className="min-h-screen p-8 pb-16">
      <Link 
        href="/" 
        className="inline-block mb-8 text-accent hover:underline"
      >
        ← Back to Home
      </Link>
      
      <div className="max-w-6xl mx-auto">
        <h1 className="text-4xl font-semibold mb-8">German Stories</h1>
        
        {isLoading ? (
          <div className="text-center py-12">
            <p className="text-lg text-text-secondary">Loading stories...</p>
          </div>
        ) : error ? (
          <div className="text-center py-12">
            <p className="text-lg text-red-500">{error instanceof Error ? error.message : 'An error occurred'}</p>
          </div>
        ) : stories && stories.length > 0 ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {stories.map(story => (
              <StoryCard key={story.id} story={story} />
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-lg text-text-secondary">No stories available yet. Check back soon!</p>
          </div>
        )}
        
        {/* Updated AI-generated content notification */}
        <div className="mt-12 mb-4 text-center">
          <p className="text-xs text-text-secondary italic">
            Stories and translations are generated by LLMs
          </p>
        </div>
      </div>
    </main>
  );
}