import StoryCard from "@/components/StoryCard";
import { getAllStories } from "@/services/storyService";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stories | Tales of Deutsch",
  description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
  openGraph: {
    title: "Stories | Tales of Deutsch",
    description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
    type: "website",
    images: [
      {
        url: "/images/tales-of-deutsch.png",
        width: 1200,
        height: 630,
        alt: "Tales of Deutsch Stories",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Stories | Tales of Deutsch",
    description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
    images: ["/images/tales-of-deutsch.png"],
  },
};

export default async function StoriesPage() {
  const stories = await getAllStories();
  
  return (
    <main className="min-h-screen p-8 pb-16">
      <Link 
        href="/" 
        className="inline-block mb-8 text-accent hover:underline"
      >
        ← Back to Home
      </Link>
      
      <div className="max-w-6xl mx-auto">
        <h1 className="text-4xl font-semibold mb-8">German Stories</h1>
        
        {stories.length > 0 ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {stories.map(story => (
              <StoryCard key={story.id} story={story} />
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-lg text-text-secondary">No stories available yet. Check back soon!</p>
          </div>
        )}
        
        {/* Updated AI-generated content notification */}
        <div className="mt-12 mb-4 text-center">
          <p className="text-xs text-text-secondary italic">
            Stories and translations are generated by LLMs
          </p>
        </div>
      </div>
    </main>
  );
}