import StoryCard from "@/components/StoryCard";
import { dummyStories } from "@/data/dummyStories";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stories | Tales of Deutsch",
  description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
  openGraph: {
    title: "Stories | Tales of Deutsch",
    description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
    type: "website",
    images: [
      {
        url: "/images/tales-of-deutsch.png",
        width: 1200,
        height: 630,
        alt: "Tales of Deutsch Stories",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Stories | Tales of Deutsch",
    description: "Explore German stories with interactive translations and word definitions to improve your language skills.",
    images: ["/images/tales-of-deutsch.png"],
  },
};

export default function StoriesPage() {
  return (
    <main className="min-h-screen p-8">
      <Link 
        href="/" 
        className="inline-block mb-8 text-accent hover:underline"
      >
        ← Back to Home
      </Link>
      
      <div className="max-w-6xl mx-auto">
        <h1 className="text-4xl font-semibold mb-8">German Stories</h1>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {dummyStories.map(story => (
            <StoryCard key={story.id} story={story} />
          ))}
        </div>
        
        {/* Subtle AI-generated content notification */}
        <div className="mt-16 pt-4 border-t border-gray-200 dark:border-gray-700 text-center opacity-75">
          <p className="text-xs text-text-secondary">
            Stories and translations are generated by LLMs.
          </p>
        </div>
      </div>
    </main>
  );
}