'use client';

import { dummyStories } from "@/data/dummyStories";
import { useState, use } from "react";
import Link from "next/link";
import ClickableText from "@/components/ClickableText";
import { Metadata } from "next";

// This function needs to be in a separate server component file
// We'll create a separate generateMetadata function in a layout.tsx file
// For now, we'll focus on the client component

export default function StoryPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const story = dummyStories.find(s => s.id === parseInt(resolvedParams.id));
  const [visibleTranslations, setVisibleTranslations] = useState<number[]>([]);

  if (!story) {
    return <div>Story not found</div>;
  }

  // Rest of the component remains the same
  const toggleTranslation = (index: number) => {
    setVisibleTranslations(prev => 
      prev.includes(index) 
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  return (
    <main className="min-h-screen p-8">
      {/* Component content remains the same */}
      <Link 
        href="/stories" 
        className="inline-block mb-8 text-accent hover:underline"
      >
        ← Back to Stories
      </Link>
      
      <article className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-semibold mb-8">{story.title}</h1>
        
        <div className="space-y-8">
          {story.content.map((paragraph, index) => (
            <div 
              key={index} 
              className="bg-card-bg rounded-lg p-6"
            >
              <ClickableText 
                text={paragraph.german} 
                className="text-lg mb-4"
              />
              
              <button
                onClick={() => toggleTranslation(index)}
                className="text-accent hover:text-accent/80 transition-colors"
              >
                {visibleTranslations.includes(index) ? 'Hide' : 'Show'} Translation
              </button>
              
              <div 
                className={`overflow-hidden transition-all duration-500 ease-in-out ${
                  visibleTranslations.includes(index) ? 'max-h-[500px] opacity-100 mt-4' : 'max-h-0 opacity-0'
                }`}
              >
                <p className="text-text-secondary italic">
                  {paragraph.english}
                </p>
              </div>
            </div>
          ))}
        </div>
        
        {/* Subtle AI-generated content notification */}
        <div className="mt-16 pt-4 border-t border-gray-200 dark:border-gray-700 text-center opacity-75">
          <p className="text-xs text-text-secondary">
            Stories and translations are generated by LLMs.
          </p>
        </div>
      </article>
    </main>
  );
}